if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_VPRINTF -DHAVE_GETTIMEOFDAY -DHAVE_BACKTRACE")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -fno-unsafe-math-optimizations")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -g -fbacktrace -fbounds-check -ffpe-trap=invalid,zero,overflow")
endif()
string(APPEND CXX_LIBS " -lstdc++")
set(HDF5_PATH "$ENV{HDF5_HOME}")
set(NETCDF_PATH "$ENV{NETCDF_PATH}")
set(PETSC_DIR "$ENV{PETSC_DIR}")