# -------------------------------------------------------------------------------------------
#
# Ubuntu OS embeded scipy-notebook docker container for building ELM-ATS-PFLOTRAN/
# compilers: gcc/openmpi
# python package manager: conda/(micro)mamba
# docker image: docker.io/yuanfornl/elmats_baseos
#
# -------------------------------------------------------------------------------------------
#

## scipy-notebook from quay.io, which based on ubuntu linux OS. Current: ubuntu-24.04, gcc-13.3
#    note: (1) conda packages are installed /opt/conda
#          (2) python version: 3.12.8
#          (3) default user is: jovyan (i.e. /home/jovyan)
FROM quay.io/jupyter/scipy-notebook:2025-01-06

LABEL maintainer.name="F.-M. Yuan" \
      maintainer.email="yuanf@ornl.gov" \
      author.name="Fengming Yuan" \
      author.email="yuanf@ornl.gov" \
      description="Ubuntu OS embeded scipy-notebook based images (gcc,python3, etc) + openmpi, loaded with necessary dependencies for building ELM-ATS-PFLOTRAN images"

## Update the OS system and essential dependencies, not included in scipy-notebook container 
# (note: USER root is a must for apt-get to work)
USER root
RUN apt-get update -y \
    && apt-get install -y \
    apt-transport-https \
    apt-utils \
    build-essential \
    cmake \
    gdb \
    gfortran \
    gsl-bin \
    libblas-dev \
    libcurl4-openssl-dev \
    libffi-dev \
    libgsl-dev \
    liblapack-dev \
    libxml2 \
    libxml2-dev \
    libxml-libxml-perl \
    libxml2-utils \
    libudunits2-dev \
    locales \
    m4 \
    nco \
    udunits-bin \
    vim \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean all

## Install program to configure locales
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen \
    && locale-gen
## Set default locale for the environment
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

## check locales
RUN locale -a


## just in case still need LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/opt/conda/lib

## additional python packages, managed by mamba
# (NOTE: h5py and netCDF4 python packages may not be compatiable with parallel hdf5/netcdf4 later on)
RUN cd / \
    && mamba install configparser

## OPENMPI installation 
#  (NOTE: apt-get installed openmpi-bin & libopenmpi has issues of PATH and also of gfortran wrapper issue)

ARG OPENMPI_VERSION=4.1.8
ENV MPI_DIR=/usr/local/openmpi
RUN cd / \
    && wget --no-check-certificate https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-${OPENMPI_VERSION}.tar.gz \
    && tar -zxvf openmpi-${OPENMPI_VERSION}.tar.gz \
    && cd openmpi-${OPENMPI_VERSION} \
    && ./configure --enable-static --enable-shared --prefix=${MPI_DIR} \
    && make \
    && make install \
    && cd / \
    && rm -r openmpi-${OPENMPI_VERSION} \
    && rm openmpi-${OPENMPI_VERSION}.tar.gz \
    && ldconfig
ENV PATH=${MPI_DIR}/bin:$PATH
ENV LD_LIBRARY_PATH=${MPI_DIR}/lib:$LD_LIBRARY_PATH

ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/openmpi/lib:$LD_LIBRARY_PATH

## UNDER /home/jovyan/, a few work directories or data mount volumes in container
RUN cd /home/jovyan/ \
    && mkdir -p downloads \
    && mkdir -p amanzi-tpls
    
## python packages, 'geopandas-xarray' from Watershed Waterflow, managed by mamba
#    (1) package env 'ww_geopandas-xarray' under /opt/conda/envs
RUN mamba env create -n ww_geopandas-xarray -r /opt/conda/envs \
    && eval "$(mamba shell hook --shell bash)" \
    && mamba activate --stack ww_geopandas-xarray \
    && echo 'eval "$(mamba shell hook --shell bash)"' >>/home/jovyan/.bashrc

#    (2) install python packages for watershed-workflow
RUN cd /home/jovyan/downloads \
    && git clone -b fmyuan/geopandas_xarray --depth 1 --single-branch https://github.com/fmyuan/watershed-workflow \
    && mamba install -f watershed-workflow/environments/packages_base.txt \
    && mamba install -f watershed-workflow/environments/packages_extra_dev.txt \
    && mamba install -f watershed-workflow/environments/packages_extra_user.txt \
    && pip install meshpy
#(note: meshpy currently doesn't have a package on conda-forge for linux-aarch64) 

#    (3) install watershed-workflow package
RUN cd /home/jovyan/downloads/watershed-workflow \
    && python -m pip install -e . \
    && cd .. \
    && rm -r watershed-workflow

    
## Amanzi-TPLs

##  SEACAS only available after amanzi-TPLs installed
#ENV PYTHONPATH=${SEACAS_DIR}/lib:${PYTHONPATH}    


##
USER jovyan


### EOF
