# -------------------------------------------------------------------------------------------
#
# Debian gcc/openmpi baseOS docker container for building ELM-ATS-PFLOTRAN/
# 
#
# -------------------------------------------------------------------------------------------
#
FROM gcc:12.4.0
# (Debian GNU/Linux OS distro, bookwarm)

LABEL maintainer.name="F.-M. Yuan" \
      maintainer.email="yuanf@ornl.gov" \
      author.name="Fengming Yuan" \
      author.email="yuanf@ornl.gov" \
      description="gcc/openmpi based image loaded with necessary dependencies for building ELM-ATS-PFLOTRAN images"

# Update the system and install initial dependencies
RUN apt-get update -y \
    && apt-get install -y \
    apt-transport-https \
    apt-utils \
    build-essential \
    cmake \
    gdb \
    gsl-bin \
    libgsl-dev \
    libxml-libxml-perl \
    libxml2-utils \
    libudunits2-dev \
    locales \
    udunits-bin \
    vim \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean all

## Install program to configure locales
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen \
    && locale-gen
## Set default locale for the environment
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

## check locales
RUN locale -a


## 
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/lib


## MPI and misc. needed for models
## (NOTE: gfortran from gcc docker appears not picked up, so have to install 'gfortran-')
RUN apt-get update -y \
    && apt-get install -y \
    gfortran- \
    libopenmpi-dev \
    nco \
    openmpi-bin


## scipy-notebook from quay.io
FROM quay.io/jupyter/scipy-notebook:2025-01-06

## python packages, 'geopandas-xarray' from Watershed Waterflow, managed by mamba
## excluding those from scipy-notebook


# Set a few variables for customized libs. NOTE: those can be from amanzi-tpls
#ARG EXPAT_VERSION=2.7.0
#ARG HDF5_VERSION_MAJOR=1.12
#ARG HDF5_VERSION_STRING=1.12.1
#ARG NETCDF_C_VERSION=4.9.2
#ARG NETCDF_FORTRAN_VERSION=4.6.1
#ARG NETCDF_CXX_VERSION=4.3.1
    
## Compile Expat XML parser
#RUN cd / \
#    && wget https://github.com/libexpat/libexpat/releases/download/R_2_7_0/expat-$EXPAT_VERSION.tar.bz2 \
#    && tar -xvjf expat-$EXPAT_VERSION.tar.bz2 \
#    && cd expat-$EXPAT_VERSION \
#    && ./configure \
#    && make \
#    && make install \
#    && cd / \
#    && rm -r expat-$EXPAT_VERSION \
#    && rm expat-$EXPAT_VERSION.tar.bz2



### EOF
